# cu-scanner 配置文件

[database]
# PostgreSQL数据库配置
host = "x.x.x.x"
port = 5432
database = "db_name"
username = "db_user"
password = "db_pass"

[csaf_url]
url="http://csaf_server/index.txt"
# 定时获取间隔（秒），默认为3600秒（1小时）
fetch_interval_secs=3600

[csaf_db]
# CSAF数据库配置
host = "x.x.x.x"
port = 5432
database = "db_name"
username = "db_user"
password = "db_pass"

[logging]
# 日志配置
level = "info"
file = "/var/log/cu-scanner.log"
# 当设置为true时，日志输出到标准输出，忽略file配置
stdout = false

[api]
# API配置
group_name = "api"

[server]
port = "8093"
# 服务器地址，默认为0.0.0.0
address = "0.0.0.0"

[package]
epoch_file="/etc/cu-scanner/epoch_data.json"
use_yum=false
use_extra_yum=false
